# -*- coding: utf-8 -*-
"""Text to Video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmQ4I8Hv1XAEhFQ3TNMvyAU_wQ2ojL_R
"""

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

!pip install modelscope==1.4.2
!pip install open_clip_torch
!pip install pytorch-lightning

from modelscope.pipelines import pipeline
from modelscope.outputs import OutputKeys

p = pipeline('text-to-video-synthesis', 'damo/text-to-video-synthesis')

test_text = {
        'text': 'A time-lapse of a flower blooming in extreme detail.',
    }
output_video_path = p(test_text,)[OutputKeys.OUTPUT_VIDEO]
print('output_video_path:', output_video_path)

# Download result
from google.colab import files
files.download(output_video_path)